name: Simon Miles
markdown: kramdown
theme: jekyll-theme-slate
title: Dr Simon Miles
description: My profile site

lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
